### ISSUE TITLE
Issue Report - CS 480

### ISSUE THREAD

**Issue by cathlinlord** [stephensonc/LiveGreenScreen#1]
### Issues
i. As you mentioned that I may not be able to during the run through, I was not able to run the program.
- [ ] Formatting/legibility/style
- [ ] Best practices
- [X] Reliability
- [X] Testability

ii. I think it would be very helpful to change the called values of colors from numbers to the color name.
This would make using the program easier for the user.
- [X] Formatting/legibility/style
- [ ] Best practices
- [ ] Reliability
- [ ] Testability

Overall, I thought this was a very creative idea and well done! Your code was easy to follow, especially because of your use of comments. The comments clearly labeled what everything's purpose was. Moving forward, I think it would be very helpful to the user to change how the color of choice is put as an input. Also, it may be nice to add additional images to the gallery, even though any added photo can be used. Lastly, addressing the issue of users not being able to run the program, although during the review in class, it was easy to navigate. Other than this, I did not see any issues with your code.

**Comment by stephensonc** [comment]
Hi Cathlin,
    Would it be possible to elaborate on what you tried in order to run the program? If you are on Windows, it is possible that you tried to run it from the run.sh shell script. <br>
    If this is the case, would it be possible to try running the program by typing in “python3 ./src/Main.py” into a command prompt terminal? If it is easier I can likely include an executable batch file to automatically run the program. 
<br>
    Additionally, I believe that the only time that colors are called as numbers is in the Color class, are there other areas that I have missed? In the write up, you mention the process of changing colors should be changed, is there anything specific that would make it easier for the user that I could implement?

**Comment by cathlinlord** [comment]
When I enter "python3 ./src/Main.py" into a terminal it comes back as "No such file or directory". I tried this from both the LiveGreenScreen and src folders. Please let me know if I should try from another location. 

What I was referring to with the colors and numbers was that I thought when in the terminal you enter a number that corresponds with a color. My thought was that there could either be a list to explain how they match up or change what you enter into the terminal to be the color name. My apologies if I am not remembering correctly!

**Comment by stephensonc** [comment]
Hi again, 
I believe that I have fixed the issues in the report, and I tested it on windows on my machine. Would it be possible for you to test the new installation instructions and see if you can run the program? 
I also added a few new backgrounds as requested in the writeup.

Thanks,
Chris Stephenson

**Comment by cathlinlord** [comment]
Hi Chris, 
I tried both set of instructions just to see if they would work and I think the problem is that I have a Mac. I was denied permission for both methods. 
Best,
Cathlin
